set-up and complete orders redux store
SuperHeroPowers/grace-shopper pull request #15
Opened 2017-07-28 01:22 UTC by haesoox3

order redux store 
approve after product/user redux store has been merged so we don't have conflicting directory structure

2017-07-28 01:30 UTC, haesoox3 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Redux store reducer for orders](https://trello.com/c/dtWH4ssp/178-redux-store-reducer-for-orders)

2017-07-28 21:48 UTC, mathildapurr commented on client/store/reducers/order.js
> +export default function (state = orders, action) {
Need action creator and thunk dispatcher for cancelling orders

2017-07-28 21:50 UTC, mathildapurr commented on client/store/reducers/order.js
> +    	return [...state, action.order];
For updated orders as well as deleted orders (to be implemented), the returned state should filter out the order by id (see products reducer)

2017-07-28 21:52 UTC, itsdanni requested changes
Need to deal with cancelling an order as well as edit the returned state from updating and cancelling orders

2017-07-28 21:54 UTC, mathildapurr commented
There are just some minor changes that need to be dealt with but github makes it look scary with the red x lol

2017-07-29 01:56 UTC, haesoox3 commented on client/store/reducers/order.js
> +export default function (state = orders, action) {
wouldn't that fall under the update order section because we're just changing the status in the model?

2017-07-29 02:15 UTC, itsdanni approved these changes
yay!

2017-07-29 02:16 UTC, merged